clang-format

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -30,9 +30,10 @@ install:
 
   # Static analysis
   - sudo apt-get install cppcheck -y
-  - if [ "${COMPILER}" = "clang" ]; then
-      sudo apt-get install clang-tidy-${COMPILER_VERSION} -y;
-      sudo apt-get install clang-format-${COMPILER_VERSION} -y;
+  - |
+    if [ "${COMPILER}" = "clang" ]; then
+      sudo apt-get install clang-tidy-${COMPILER_VERSION} -y
+      sudo apt-get install clang-format-${COMPILER_VERSION} -y
     fi
 
 before_build:
@@ -54,17 +55,22 @@ build_script:
 after_build:
   # Cannot activate --error-exitcode=1 as there's false positive (16.04)
   - cppcheck --enable=all --inline-suppr --suppress=missingIncludeSystem ../${APPVEYOR_PROJECT_NAME}/
-  - if [ "${COMPILER}" = "clang" ]; then
-      find ../${APPVEYOR_PROJECT_NAME}/* -name '*.cpp' -not -name 'CMakeCXXCompilerId.cpp' -or -name '*.h' -or -name '*.hxx' | xargs clang-format -i;
-      find ../${APPVEYOR_PROJECT_NAME}/* -name '*.cpp' -not -name 'CMakeCXXCompilerId.cpp' | xargs clang-tidy -p ./ -config '';
+  - |
+    if [ "${COMPILER}" = "clang" ]; then
+      find ../${APPVEYOR_PROJECT_NAME}/* -name '*.cpp' -not -name 'CMakeCXXCompilerId.cpp' -or -name '*.h' -or -name '*.hxx' | xargs clang-format -style=file -output-replacements-xml | grep "<replacement " > /dev/null
+      if [ $? -ne 1 ]; then
+        echo "Formatting change required by clang-format!"
+      fi
+      find ../${APPVEYOR_PROJECT_NAME}/* -name '*.cpp' -not -name 'CMakeCXXCompilerId.cpp' | xargs clang-tidy-${COMPILER_VERSION} -p ./ -config ''
     fi
 
 test_script:
   - ctest -V
 
 after_test:
-  - if [ "${CONFIGURATION}" == "Release" ]; then
-      ./bin/benchmark_${APPVEYOR_PROJECT_NAME};
+  - |
+    if [ "${CONFIGURATION}" == "Release" ]; then
+      ./bin/benchmark_${APPVEYOR_PROJECT_NAME}
     fi
 
 # - TODO:
